### ISSUE TITLE
How to apply CSS Used to the local file or localhost?

### ISSUE THREAD

**Issue by gusbemacbe** [painty/CSS-Used-ChromeExt#3]
I downloaded a template, I used Pinegrow or Google Chrome to copy each determined and specified in the specified page so I didn't want to use the whole CSS, but they are many things. I tried to run your plugin for a local file (for example: file://Users//......./index.html

**Comment by painty** [comment]
Due to Chrome's default policy, extensions don't have permission to access local files.

Active it manually:

Go to [chrome://extensions/](chrome://extensions/) and Check the "Allow access to file URLs"
![CSS Used file access](https://user-images.githubusercontent.com/5387771/29500888-e7a1fe48-8656-11e7-98e4-69d20e4fa7ce.jpg)

**Comment by gusbemacbe** [comment]
Sorry for my absence because of my college. Unfortunately it didn't work, following the instructions.
