### ISSUE TITLE
responsive web design CSS doesn't work correctly.

### ISSUE THREAD

**Issue by emmastone9** [painty/CSS-Used-ChromeExt#6]
Go to any RWD website: https://techcrunch.com/
Select the top nav bar class, "nav-bar" in this case.
Click on CSS Used -> Local Preview.
The preview window doesn't show the mobile version of the nav-bar, it shows the desktop version.
Resizing the window doesn't help either.

**Comment by emmastone9** [comment]
Hey @painty ,
Bit confused, how would I go about using the `web tools inspector` with respect to .wrap? Can you please elaborate more?

**Comment by painty** [comment]
![-1](https://user-images.githubusercontent.com/5387771/33716080-be0577ac-db8f-11e7-87d8-8cd67fb6c08f.gif)
For example, the css rule with selector `.header .header-social` only works when `<div class="header-social">`  is under `<header class="header ...`.

In your case , you select "nav-bar" and click  CSS Used -> Local Preview.

In the preview window, the HTML would be `<div class="nav-bar"> ...<div class="header-social">...` , The selector `.header .header-social` will apply to none of the elements( because there is no `.header` in the selected HTML).

'CSS Used`  tool only helps you to get the used css rules, while how css rules work depends on the html.

BTW, If you want to copy EXACTLY the same looks, try [SnappySnippet](https://chrome.google.com/webstore/detail/snappysnippet/blfngdefapoapkcdibbdkigpeaffgcil?hl=en) , which traverses every style property of every element and GENERATE rules: one element one id, one id one set of styles (can always get the same look but no practicably use on production).
